const images = {
  nationalAssembly: {
    image: "/assets/images/projects/national-assembly.webp",
    imageAlt: "National Assembly Complex in Abuja",
    imageContext: "Project location",
    imageSource: "Wikimedia Commons",
    imageSourceUrl:
      "https://commons.wikimedia.org/wiki/File:National_Assembly_Complex,_Abuja.jpg",
  },
  rmrdc: {
    image: "/assets/images/projects/rmrdc.webp",
    imageAlt: "Raw Materials Research and Development Council building in Abuja",
    imageContext: "Project location",
    imageSource: "Leadership News",
    imageSourceUrl:
      "https://leadership.ng/rmrdc-defence-hq-to-boost-food-security/",
  },
  abuja: {
    image: "/assets/images/projects/abuja-skyline.webp",
    imageAlt: "View across Abuja",
    imageContext: "Abuja location view",
    imageSource: "Wikimedia Commons",
    imageSourceUrl: "https://commons.wikimedia.org/wiki/File:Abuja_skyline.jpg",
  },
  defenceCollege: {
    image: "/assets/images/projects/national-defence-college.webp",
    imageAlt: "National Defence College entrance in Abuja",
    imageContext: "Project location",
    imageSource: "SabiAbuja",
    imageSourceUrl: "https://sabiabuja.com/national-defence-college-abuja/",
  },
  nysc: {
    image: "/assets/images/projects/nysc-headquarters.webp",
    imageAlt: "National Youth Service Corps headquarters in Abuja",
    imageContext: "Project location",
    imageSource: "Wikimedia Commons",
    imageSourceUrl:
      "https://commons.wikimedia.org/wiki/File:NYSC_Headquarters,_Abuja.jpg",
  },
  lekki: {
    image: "/assets/images/projects/lekki.webp",
    imageAlt: "Lekki Link Bridge illuminated at night",
    imageContext: "Lekki location view",
    imageSource: "Wikimedia Commons",
    imageSourceUrl:
      "https://commons.wikimedia.org/wiki/File:Lekki_link_bridge_at_night.jpg",
  },
  zaranda: {
    image: "/assets/images/projects/zaranda-hotel.webp",
    imageAlt: "Zaranda Hotel in Bauchi",
    imageContext: "Project location",
    imageSource: "Wikimedia Commons",
    imageSourceUrl:
      "https://commons.wikimedia.org/wiki/File:Zaranda_hotel_bauchi_nigeria_-_panoramio.jpg",
  },
  victoriaIsland: {
    image: "/assets/images/projects/victoria-island.webp",
    imageAlt: "Aerial view of Victoria Island in Lagos",
    imageContext: "Victoria Island location view",
    imageSource: "Wikimedia Commons",
    imageSourceUrl:
      "https://commons.wikimedia.org/wiki/File:Aerial_view_of_victoria_island_in_Lagos,_Nigeria.jpg",
  },
};

module.exports = [
  {
    client: "National Assembly of the Federal Republic of Nigeria",
    location: "Three Arms Zone, Abuja",
    year: "2008",
    scope: "Supply of three Mitsubishi elevators to the House of Representatives.",
    category: "Government",
    filter: "installation",
    service: "Supply & installation",
    ...images.nationalAssembly,
  },
  {
    client: "National Assembly of the Federal Republic of Nigeria",
    location: "Three Arms Zone, Abuja",
    year: "2008",
    scope: "Two-year maintenance programme for five House of Representatives elevators.",
    category: "Government",
    filter: "maintenance",
    service: "Maintenance",
    ...images.nationalAssembly,
  },
  {
    client: "Raw Materials Research and Development Council",
    location: "Abuja",
    year: "2014",
    scope: "Supply and installation of two Shanghai Mitsubishi elevators.",
    category: "Government",
    filter: "installation",
    service: "Supply & installation",
    ...images.rmrdc,
  },
  {
    client: "Raw Materials Research and Development Council",
    location: "Abuja",
    year: "2015",
    scope: "Repair and maintenance of the existing lift at the Raw Materials building.",
    category: "Government",
    filter: "maintenance",
    service: "Repair & maintenance",
    ...images.rmrdc,
  },
  {
    client: "National Integrated Power Project",
    location: "Abuja",
    year: "2010",
    scope: "Maintenance of four machine-room-less Mitsubishi-brand elevators.",
    category: "Infrastructure",
    filter: "maintenance",
    service: "Maintenance",
    ...images.abuja,
  },
  {
    client: "Nigerian Air Force Headquarters",
    location: "Abuja",
    year: "2010",
    scope: "Supply and installation of three Shanghai Mitsubishi elevators.",
    category: "Government",
    filter: "installation",
    service: "Supply & installation",
    ...images.abuja,
  },
  {
    client: "National Defence College",
    location: "Abuja",
    year: "2009",
    scope: "Supply and installation of two elevators through Stabilini Visinoni Limited.",
    category: "Government",
    filter: "installation",
    service: "Supply & installation",
    ...images.defenceCollege,
  },
  {
    client: "Nigerian Agricultural and Rural Development Bank Plaza",
    location: "Abuja",
    year: "2008",
    scope: "Replacement of two elevators through Muhammad & Co.",
    category: "Commercial",
    filter: "modernization",
    service: "Elevator replacement",
    ...images.abuja,
  },
  {
    client: "National Youth Service Corps Headquarters",
    location: "Abuja",
    year: "2009",
    scope: "Supply and installation of two elevators at the headquarters office complex.",
    category: "Government",
    filter: "installation",
    service: "Supply & installation",
    ...images.nysc,
  },
  {
    client: "HDIC Training Centre",
    location: "Lekki Phase 1, Lagos",
    year: "2016",
    scope: "Supply of five elevators through Pag Ferrero & Co.",
    category: "Commercial",
    filter: "installation",
    service: "Elevator supply",
    ...images.lekki,
  },
  {
    client: "INCAR Nigeria Limited",
    location: "Abuja",
    year: "2009",
    scope: "Supply and installation of four escalators and one cleaning cradle.",
    category: "Commercial",
    filter: "escalators",
    service: "Escalators & cradle",
    ...images.abuja,
  },
  {
    client: "National Defence College",
    location: "Abuja",
    year: "2010",
    scope: "Supply and installation of two elevators through CGGC Global Projects Nigeria Limited.",
    category: "Government",
    filter: "installation",
    service: "Supply & installation",
    ...images.defenceCollege,
  },
  {
    client: "Zaranda Hotel",
    location: "Bauchi",
    year: "2008",
    scope: "Elevator maintenance services.",
    category: "Hospitality",
    filter: "maintenance",
    service: "Maintenance",
    ...images.zaranda,
  },
  {
    client: "Addax Petroleum",
    location: "Victoria Island, Lagos",
    year: "2011",
    scope: "Maintenance of two lift facilities.",
    category: "Commercial",
    filter: "maintenance",
    service: "Maintenance",
    ...images.victoriaIsland,
  },
  {
    client: "Castle Home",
    location: "Victoria Island, Lagos",
    year: "2016",
    scope: "Maintenance of one elevator through AM Facilities and Management Limited.",
    category: "Residential",
    filter: "maintenance",
    service: "Maintenance",
    ...images.victoriaIsland,
  },
];
