module.exports = {
  name: "Everest World Lifts",
  shortName: "Everest World Lifts",
  url: process.env.URL || "https://www.everestworldlifts.com",
  description:
    "Elevator, escalator, and moving walkway distribution, installation, maintenance, modernization, and consulting services in Nigeria.",
  incorporated: "June 2006",
  renamed: "February 2019",
  registrationNumber: "RC 1560172",
  originalRegistrationNumber: "RC 656022",
  address: "8 Bello Gaya Street, Lifecamp, Abuja, Nigeria",
  phone: "+234 701 202 0201",
  phoneHref: "+2347012020201",
  emergencyPhone: "+234 815 556 6609",
  emergencyPhoneHref: "+2348155566609",
  email: "info@everestworldlifts.com",
  supportEmail: "support@everestworldlifts.com",
  deliveryArea: "We deliver nationwide",
  businessHours: [
    "Monday-Friday (excluding public holidays)",
    "9:00 AM-1:00 PM",
    "2:00 PM-5:30 PM",
    "Saturday 10:00 AM-12:30 PM",
  ],
  social: [
    {
      label: "Facebook",
      url: "https://www.facebook.com/share/1H2jNaAuse/",
    },
    {
      label: "Instagram",
      url: "https://www.instagram.com/everestworldliftsltd?igsh=b3RqY3k4c3g5ZWh5",
    },
  ],
  navigation: [
    { key: "home", label: "Home", url: "/" },
    { key: "about", label: "About", url: "/about/" },
    { key: "products", label: "Products", url: "/products/" },
    { key: "services", label: "Services", url: "/services/" },
    { key: "projects", label: "Projects", url: "/projects/" },
    { key: "blog", label: "Blog", url: "/blog/" },
    { key: "contact", label: "Contact", url: "/contact/" },
  ],
  companyNavigation: [
    { label: "About Us", url: "/about/" },
    { label: "Projects", url: "/projects/" },
    { label: "Blog", url: "/blog/" },
    { label: "Careers", url: "/careers/" },
    { label: "Contact Us", url: "/contact/" },
    { label: "FAQs", url: "/faq/" },
  ],
  policyNavigation: [
    { label: "Policies", url: "/policies/" },
    { label: "Privacy Policy", url: "/privacy/" },
    { label: "Terms & Conditions", url: "/terms/" },
  ],
};
